---
title: "testing_inla_mcmc"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{testing_inla_mcmc}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(inlamisclass)
library(ggplot2)
```


```{r}
# Misclassification in smoking status assumed
MC_matrix <- matrix(c(0.95, 0.05, 0.2, 0.8), nrow = 2, byrow = T)

p <- 0.4
alpha <- c(log(p/(1-p)), 0)

birthweight_model <- inla_mcmc(formula_moi = bwt ~ smoke + lwt,
                               formula_imp = smoke ~ lwt,
                               alpha = alpha, MC_matrix = MC_matrix,
                               data = birthweight, niter = 3, nburnin = 1)

make_results_df(birthweight_model, niter = 3, nburnin = 1)$moi
```

```{r}
birthweight_model_is <- inla_is(formula_moi = bwt ~ smoke + lwt,
                               formula_imp = smoke ~ lwt,
                               alpha = alpha, MC_matrix = MC_matrix,
                               data = birthweight, niter = 3, ncores = 4)

is_results <- make_results_df(birthweight_model_is, niter = 3)
```

```{r}
naive_mod <- INLA::inla(bwt ~ smoke + lwt, data = birthweight)

plot_compare_inlamisclass(birthweight_model_is, naive_mod = naive_mod)
```

```{r}
birthweight_model1 <- inla_is(formula_moi = bwt ~ smoke + lwt,
                              formula_imp = smoke ~ lwt,
                              alpha = c(log(0.4/(1-0.4)), 0),
                              MC_matrix = MC_matrix,
                              data = birthweight, niter = 3)
birthweight_model2 <- inla_is(formula_moi = bwt ~ smoke + lwt,
                                formula_imp = smoke ~ lwt,
                                alpha = c(-3, 0.02),
                                MC_matrix = MC_matrix,
                                data = birthweight, niter = 3)

plot_compare_inlamisclass(mcmc_results = list(inlamisclass1 = birthweight_model1, 
                               inlamisclass2 = birthweight_model2), 
                          naive_mod = naive_mod, niter = 3, num_inlamisclass_models = 2)


```

```{r}
library(inlamisclass)
library(dplyr)
library(INLA)

validation <- filter(case_control_data, !is.na(x))
complete_data <- filter(case_control_data, is.na(x))

# Estimates misclassification matrix without accounting for y
# w = 1 given x = 0
pi10 <- sum((validation$w-validation$x) == 1)/sum(validation$x==0)

# w = 0, given x = 1, y = 1
pi01 <- sum(validation$w-validation$x == -1)/sum(validation$x==1)

M <- matrix(c(1-pi10, pi10, pi01, 1-pi01), byrow = TRUE, nrow = 2)
M

exp_mod <- inla(x~1, data = validation, family = "binomial", Ntrials = 1)
exp_mod$summary.fixed

case_control_model <- inla_is(formula_moi = d ~ w,
                              formula_imp = w ~ 1,
                              alpha = -0.08775608,
                              MC_matrix = M,
                              data = complete_data,
                              niter = 3, 
                              family = "binomial", Ntrials = 1)

make_results_df(case_control_model)$moi

naive_cc <- inla(d ~ w, data = complete_data, family = "binomial", Ntrial = 1)
naive_cc$summary.fixed

plot_compare_inlamisclass(case_control_model, naive_mod = naive_cc, plot_intercept = TRUE)
```

```{r}
# Conditional model to deal with differential MC in case-control data

library(inlamisclass)
library(dplyr)
library(INLA)

validation <- filter(case_control_data, !is.na(x))
incomplete_data <- filter(case_control_data, is.na(x))

validation1 <- filter(validation, y == 1)
validation0 <- filter(validation, y == 0)

# w = 1 given x = 0, y = 1
pi10_y1 <- sum((validation1$w-validation1$x) == 1)/sum(validation1$x==0)
# w = 0, given x = 1, y = 1
pi01_y1 <- sum(validation1$w-validation1$x == -1)/sum(validation1$x==1)

# w = 1, x = 0, given y = 0
pi10_y0 <- sum((validation0$w-validation0$x) == 1)/sum(validation0$x==0)
# w = 0, x = 1, given y = 0
pi01_y0 <- sum(validation0$w-validation0$x == -1)/sum(validation0$x==1)


M1 <- matrix(c(1-pi10_y1, pi10_y1, pi01_y1, 1-pi01_y1), byrow = TRUE, nrow = 2)
M1

M0 <- matrix(c(1-pi10_y0, pi10_y0, pi01_y0, 1-pi01_y0), byrow = TRUE, nrow = 2)
M0

alphas <- glm(x~y, family = "binomial", data = validation)$coef

case_control_model <- inla_is(formula_moi = y ~ w,
                              formula_imp = w ~ y,
                              alpha = alphas,
                              MC_matrix = list(MC_1 = M1, MC_0 = M0),
                              data = incomplete_data,
                              niter = 3,
                              conditional = TRUE,
                              family = "binomial", Ntrials = 1)

```





